name: Test

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '2.6.8'
          - '2.7.4'
          - '3.0.2'
        rails:
          - '5.2'
          - '6.0'
          - '6.1'

    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby ${{ matrix.ruby }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Setup Bundler
        run: |
          gem update --system --no-doc
          gem install bundler --no-doc
          bundle config set path "vendor/bundle"

      # - name: Setup Code Climate
      #   run: |
      #     curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      #     chmod +x ./cc-test-reporter
      #     ./cc-test-reporter before-build

      - name: Restore Gem Cache
        id: gem-cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: gem-cache:${{ runner.os }}-${{ matrix.ruby }}-${{ matrix.rails }}
          restore-keys: |
            gem-cache:${{ runner.os }}-${{ matrix.ruby }}-${{ matrix.rails }}

      - name: Install Gems for Rails ${{ matrix.rails }}
        env:
          BUNDLE_GEMFILE: gemfiles/${{ matrix.rails }}.gemfile
        run: |
          bundle check || bundle install --jobs 4 --retry 3

      - name: Run Test Suite
        env:
          BUNDLE_GEMFILE: gemfiles/${{ matrix.rails }}.gemfile
        run: |
          bundle exec rake

      # - name: Upload Coverage Report
      #   run: |
      #     export GIT_BRANCH="${GITHUB_REF/refs\/heads\//}"
      #     ./cc-test-reporter after-build -r ${{secrets.CC_TEST_REPORTER_ID}}
